[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
remappings = [
  "solady/src/=lib/solady/src/",
  "solady/test/=lib/solady/test/"
]
solc_version = "0.8.25"
viaIR = false
optimizer_runs = 1_000_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
